PREFIX cbhsv: <http://data.builthub.eu/ontology/cbhsv#>
PREFIX ns72: <http://data.europa.eu/nuts/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX nuts: <http://data.europa.eu/nuts/code/>
SELECT DISTINCT ?siec ?Austria ?Belgium ?Bulgaria
WHERE{
{
SELECT ?siec ((((?value1*(?value2/100))*100000)/?value3) AS ?Austria)
WHERE{
  {
 SELECT DISTINCT ?locationName ?value1
WHERE {
	?s	a cbhsv:Dataset014 ;
  		dct:temporal/dcat:startDate "2019-01-01"^^xsd:date ;
		dcat:spatial/skos:prefLabel ?locationName ;
		dcat:spatial/skos:prefLabel "Austria"@en ;
      	cbhsv:siec/skos:prefLabel ?siec ;
		cbhsv:measurementValue ?value1 .
          FILTER (lang(?locationName) = 'en')
}
}
{
  SELECT ?locationName ?value2 ?siec
WHERE {
	?s	a cbhsv:Dataset015 ;
        cbhsv:hasNUTS/ns72:level '0.0'^^xsd:decimal ;
  		dct:temporal/dcat:startDate "2019-01-01"^^xsd:date ;
		dcat:spatial/skos:prefLabel ?locationName ;
		dcat:spatial/skos:prefLabel "Austria"@en ;
      	cbhsv:siec/skos:prefLabel ?siec ;
		cbhsv:measurementValue ?value2 .
          FILTER (lang(?locationName) = 'en')
}
}
{
    SELECT DISTINCT ?locationName ?value3 ?measuredElement ?startDate
WHERE {
	?s	a cbhsv:Dataset026 ;
        cbhsv:hasNUTS/ns72:level '0.0'^^xsd:decimal ;
  		dct:temporal/dcat:startDate "2019-01-01"^^xsd:date ;
		dcat:spatial/skos:prefLabel ?locationName ;
		dcat:spatial/skos:prefLabel "Austria"@en ;
		cbhsv:measuredElement <http://purl.org/linked-data/sdmx/2009/code#sex-T> ;
		cbhsv:measurementValue ?value3 .
          FILTER (lang(?locationName) = 'en')
}
}
}
}
{
SELECT ?siec ((((?value1*(?value2/100))*100000)/?value3) AS ?Belgium)
WHERE{
  {
 SELECT DISTINCT ?locationName ?value1
WHERE {
	?s	a cbhsv:Dataset014 ;
  		dct:temporal/dcat:startDate "2019-01-01"^^xsd:date ;
		dcat:spatial/skos:prefLabel ?locationName ;
		dcat:spatial/skos:prefLabel "Belgium"@en ;
      	cbhsv:siec/skos:prefLabel ?siec ;
		cbhsv:measurementValue ?value1 .
          FILTER (lang(?locationName) = 'en')
}
}
{
  SELECT ?locationName ?value2 ?siec
WHERE {
	?s	a cbhsv:Dataset015 ;
        cbhsv:hasNUTS/ns72:level '0.0'^^xsd:decimal ;
  		dct:temporal/dcat:startDate "2019-01-01"^^xsd:date ;
		dcat:spatial/skos:prefLabel ?locationName ;
		dcat:spatial/skos:prefLabel "Belgium"@en ;
      	cbhsv:siec/skos:prefLabel ?siec ;
		cbhsv:measurementValue ?value2 .
          FILTER (lang(?locationName) = 'en')
}
}
{
    SELECT DISTINCT ?locationName ?value3 ?measuredElement ?startDate
WHERE {
	?s	a cbhsv:Dataset026 ;
        cbhsv:hasNUTS/ns72:level '0.0'^^xsd:decimal ;
  		dct:temporal/dcat:startDate "2019-01-01"^^xsd:date ;
		dcat:spatial/skos:prefLabel ?locationName ;
		dcat:spatial/skos:prefLabel "Belgium"@en ;
		cbhsv:measuredElement <http://purl.org/linked-data/sdmx/2009/code#sex-T> ;
		cbhsv:measurementValue ?value3 .
          FILTER (lang(?locationName) = 'en')
}
}
}
}
{
SELECT ?siec ((((?value1*(?value2/100))*100000)/?value3) AS ?Bulgaria)
WHERE{
  {
 SELECT DISTINCT ?locationName ?value1
WHERE {
	?s	a cbhsv:Dataset014 ;
  		dct:temporal/dcat:startDate "2019-01-01"^^xsd:date ;
		dcat:spatial/skos:prefLabel ?locationName ;
		dcat:spatial/skos:prefLabel "Bulgaria"@en ;
      	cbhsv:siec/skos:prefLabel ?siec ;
		cbhsv:measurementValue ?value1 .
          FILTER (lang(?locationName) = 'en')
}
}
{
  SELECT ?locationName ?value2 ?siec
WHERE {
	?s	a cbhsv:Dataset015 ;
        cbhsv:hasNUTS/ns72:level '0.0'^^xsd:decimal ;
  		dct:temporal/dcat:startDate "2019-01-01"^^xsd:date ;
		dcat:spatial/skos:prefLabel ?locationName ;
		dcat:spatial/skos:prefLabel "Bulgaria"@en ;
      	cbhsv:siec/skos:prefLabel ?siec ;
		cbhsv:measurementValue ?value2 .
          FILTER (lang(?locationName) = 'en')
}
}
{
    SELECT DISTINCT ?locationName ?value3 ?measuredElement ?startDate
WHERE {
	?s	a cbhsv:Dataset026 ;
        cbhsv:hasNUTS/ns72:level '0.0'^^xsd:decimal ;
  		dct:temporal/dcat:startDate "2019-01-01"^^xsd:date ;
		dcat:spatial/skos:prefLabel ?locationName ;
		dcat:spatial/skos:prefLabel "Bulgaria"@en ;
		cbhsv:measuredElement <http://purl.org/linked-data/sdmx/2009/code#sex-T> ;
		cbhsv:measurementValue ?value3 .
          FILTER (lang(?locationName) = 'en')
}
}
}
}
}
ORDER BY ?siec

