PREFIX blthb: <https://data.builthub.eu/ontology/cbhsv#>
prefix dcat: <http://www.w3.org/ns/dcat#>
prefix dc: <http://purl.org/dc/elements/1.1/>
prefix dct: <http://purl.org/dc/terms/>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix siec: <http://dd.eionet.europa.eu/vocabulary/eurostat/siec/>
prefix nuts: <http://data.europa.eu/nuts/>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix adms: <http://www.w3.org/ns/adms#>
prefix rdf:	<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix cbhsv: <https://data.builthub.eu/ontology/cbhsv#>

SELECT DISTINCT ?pop_nuts0 ?count ?count2
WHERE {
    {
  SELECT DISTINCT ?datasetName ?pop_nuts0 (count(?pop_nuts0) as ?count)
WHERE {
	?s	a cbhsv:Dataset014 ;
		dc:identifier ?identifier ;
        cbhsv:hasNUTS/dc:identifier ?nutsID ;
        rdf:type/rdfs:label ?datasetName ;
  		dct:temporal/dcat:startDate ?startDate ;
  		dct:temporal/dcat:endDate ?endDate ;
		dcat:spatial/skos:prefLabel ?location ;
		cbhsv:measuredElement ?measuredElement;
      	cbhsv:siec/skos:prefLabel ?siec ;
		cbhsv:measurementUnit ?msrUnit;
		cbhsv:measurementValue ?msrValue .
		
  	OPTIONAL {?s cbhsv:hasNUTS/nuts:level ?nutsLevel }
  	OPTIONAL {?s cbhsv:hasNUTS/skos:prefLabel ?nutsName }
  	OPTIONAL {?s dct:accrualPeriodicity/skos:prefLabel ?periodicity }
 	FILTER (lang(?location) = 'en')
	FILTER (lang(?periodicity) = 'en')
  BIND(SUBSTR(?nutsID,1,2) as ?pop_nuts0) 
}
GROUP BY ?pop_nuts0 ?datasetName
  }
  {
    SELECT DISTINCT ?datasetName2 ?pop_nuts0 (count(?pop_nuts0) as ?count2)
WHERE {
	?s	a cbhsv:Dataset026 ;
		dc:identifier ?identifier ;
        cbhsv:hasNUTS/dc:identifier ?nutsID ;
        rdf:type/rdfs:label ?datasetName2 ;
  		dct:temporal/dcat:startDate ?startDate ;
  		dct:temporal/dcat:endDate ?endDate ;
		dcat:spatial/skos:prefLabel ?location ;
		cbhsv:availableFlag ?availableFlag ;
		cbhsv:measuredElement ?measuredElement ;
		cbhsv:measurementUnit ?msrUnit;
		cbhsv:measurementValue ?msrValue .

  	OPTIONAL {?s cbhsv:hasNUTS/nuts:level ?nutsLevel }
  	OPTIONAL {?s cbhsv:hasNUTS/skos:prefLabel ?nutsName }
  	
	FILTER (lang(?location) = 'en')
  BIND(SUBSTR(?nutsID,1,2) as ?pop_nuts0) 
	FILTER (str(?pop_nuts0) != 'NA')
}
GROUP BY ?pop_nuts0 ?datasetName2
  }
}
ORDER BY ?pop_nuts0
